export const UPDATE_BOUNDINGBOXES = 'UPDATE_BOUNDINGBOXES';

export const INIT_DETECTED_ANOMALIES = 'INIT_DETECTED_ANOMALIES';
export const INIT_DETECTED_OBJECTS = 'INIT_DETECTED_OBJECTS';
export const INIT_VIDEO = 'INIT_VIDEO';
