export const VIDEO_INIT = 'VIDEO_INIT';
export const FETCH_VIDEO_START = 'FETCH_VIDEO_START';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_ERROR = 'FETCH_VIDEO_ERROR';

export const VIDEOS_INIT = 'VIDEOS_INIT';
export const FETCH_VIDEOS_START = 'FETCH_VIDEOS_START';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_ERROR = 'FETCH_VIDEOS_ERROR';

export const INIT_BOUNDINGBOXES = 'INIT_BOUNDINGBOXES';
export const INIT_DETECTED_ANOMALIES = 'INIT_DETECTED_ANOMALIES';
export const INIT_DETECTED_OBJECTS = 'INIT_DETECTED_OBJECTS';
